下面这段代码输出什么？

```
func f(n int) (r int) { 
    defer func() {       
        r += n        
        recover()   
    }()    
    
var f func()    
defer f()    
   f = func() {     
       r += 2   
   }    
   return n + 1
}
func main() {  
    fmt.Println(f(3))
}
```

```
答案：7
recover()(让进入宕机流程中的goroutine恢复过来)仅用在defer()函数中，正常执行过程中，调用recover会返回nil并且没有其他任何效果，如果当前的 goroutine 陷入崩溃，调用 recover 可以捕获到 panic 的输入值，并且恢复正常的执行。
我写的是9。根据之前的笔记，将return语句分为三步：1- r=n+1=3+1=4;2- 接着执行第二个defer，但是此时f()未定义,引发异常；3- 随即执行第一个defer，异常被recover()捕获，程序正常执行，返回return。
```



下面这段代码输出什么？

```
func main() {   
    var a = [5]int{1, 2, 3, 4, 5}   
    var r [5]int   
    for i, v := range a {       
        if i == 0 {         
            a[1] = 12           
            a[2] = 13      
            }       
        r[i] = v   
     }   
     fmt.Println("r = ", r)   
     fmt.Println("a = ", a)
}
```

```
答案：
r = [1 2 3 4 5]
a = [1 12 13 4 5]
数组可以通过下标去访问。
range 表达式是副本参与循环，就是说例子中参与循环的是 a 的副本，而不是真正的 a。就这个例子来说，假设 b 是 a 的副本，则 range 循环代码是这样的：

for i, v := range b {
    if i == 0 {
        a[1] = 12
        a[2] = 13
    }
    r[i] = v
}
因此无论 a 被如何修改，其副本 b 依旧保持原值，并且参与循环的是 b，因此 v 从 b 中取出的仍旧是 a 的原值，而非修改后的值
```









